server:
  port: 8900
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ABtank/cloud-config-sever
#          uri: file://@project.basedir@/config-repository
#          uri: file:///${user.home}/config-repository
          username: abtank
          password: Z4Vesrfd1.