DROP TABLE IF EXISTS products CASCADE;
GO

DROP TABLE IF EXISTS brands CASCADE;
GO

DROP TABLE IF EXISTS categories CASCADE;
GO

DROP TABLE IF EXISTS statuses CASCADE;
GO

DROP TABLE IF EXISTS product_types CASCADE;
GO