POST http://localhost:8182/send?user=first.user

Some text message to second user

###
POST http://localhost:8181/send?user=second.user

Some text message to first user

###
POST http://localhost:8181/send?user=third.user

Some text message
